### ISSUE TITLE
Confirming, this only works on iOS 16+?

### ISSUE THREAD

**Issue by Jonovono** [Cindori/FluidGradient#4]
Looks really cool, but not going 16+ just yet, but looking forward to using it.

**Comment by joogps** [comment]
Hi @Jonovono! Sorry for missing this issue, and thank you for finding out about it!

I forgot to fix the system versions when setting up this project as a Package. So, now, the minimum versions are iOS 14 and macOS Big Sur (and I've added badges in the readme to make it clear haha). It should work fine on those versions but I haven't tested either in the simulator or on an actual device, so let me know if you find any issues.

The example app is still iOS 16+ because it uses some specific colors and new methods (also its minimum version is not critical).
